# Generated by Django 4.0.5 on 2022-06-04 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_1', models.CharField(max_length=50)),
                ('asset_2', models.CharField(max_length=50)),
                ('asset_3', models.CharField(max_length=50)),
                ('asset_4', models.CharField(max_length=50)),
                ('asset_5', models.CharField(max_length=50)),
                ('asset_6', models.CharField(max_length=50)),
                ('asset_7', models.CharField(max_length=50)),
                ('asset_8', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField(blank=True)),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField(blank=True)),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('partner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField(blank=True)),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='travelagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('reside_in_pakistan', models.BooleanField()),
                ('business_foreign_name', models.CharField(blank=True, max_length=200)),
                ('business_foreign_address', models.CharField(blank=True, max_length=200)),
                ('nature_of_firm', models.CharField(choices=[('proprietary', 'Proprietary'), ('partnership', 'Partnership'), ('private company', 'Private Company'), ('limited', 'Limited'), ('unlimited', 'Unlimited')], default='private company', max_length=200)),
                ('year_of_establishment', models.DateField(default=datetime.date.today)),
                ('registration_copy', models.FileField(default=0, upload_to='')),
                ('contact_number', models.IntegerField(default=0)),
                ('cable_address', models.CharField(default=0, max_length=200)),
                ('other_branch', models.BooleanField(default=False)),
                ('branch_code', models.IntegerField(default=0)),
                ('branch_address', models.CharField(default=0, max_length=200)),
                ('investment', models.IntegerField(default=0)),
                ('investment_copy', models.FileField(default=0, upload_to='')),
                ('banker_name', models.CharField(default=0, max_length=200)),
                ('reference_letter_copy', models.FileField(default=0, upload_to='')),
                ('auditor_name', models.CharField(default=0, max_length=30)),
                ('auditor_number', models.IntegerField(default=0)),
                ('auditors_address', models.CharField(default=0, max_length=200)),
                ('Number_of_directors', models.IntegerField(default=1)),
                ('Number_of_managers', models.IntegerField(default=1)),
                ('Number_of_partners', models.IntegerField(default=1)),
                ('general_staff', models.IntegerField(default=1)),
                ('business_1', models.CharField(max_length=200, null=True)),
                ('business_2', models.CharField(max_length=200, null=True)),
                ('business_3', models.CharField(max_length=200, null=True)),
                ('business_4', models.CharField(blank=True, max_length=200)),
                ('business_5', models.CharField(blank=True, max_length=200)),
                ('no_of_foreign_partnerships', models.IntegerField(blank=True, default=0)),
                ('partnership_file', models.FileField(default=0, upload_to='')),
                ('foreign_dealing', models.BooleanField(default=False)),
                ('exchange_licence_number', models.IntegerField(blank=True, default=0)),
                ('issue_date', models.DateField(blank=True, default=datetime.date.today)),
                ('exchange_address', models.CharField(default=0, max_length=200)),
                ('license_copy', models.FileField(blank=True, upload_to='')),
                ('exchange_statment', models.FileField(blank=True, upload_to='')),
                ('conviction_details', models.CharField(blank=True, max_length=500)),
                ('business_plan_copy', models.FileField(default=0, upload_to='')),
            ],
        ),
    ]
