# Generated by Django 4.0.3 on 2022-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restraunt_name', models.CharField(max_length=100, null=True)),
                ('establisment_date', models.DateField()),
                ('commission_date', models.DateField()),
                ('telex_num', models.IntegerField(null=True)),
                ('telephone_num', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('telegraphic_num', models.IntegerField(null=True)),
                ('province', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=10)),
                ('town', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
