# Generated by Django 4.0.5 on 2022-06-30 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms_type', models.CharField(blank=True, default='Wood', max_length=100, null=True)),
                ('rooms_type', models.CharField(blank=True, default='Wood', max_length=100, null=True)),
                ('corridors_type', models.CharField(blank=True, default='Wood', max_length=100, null=True)),
                ('attached_bathroom_type', models.CharField(blank=True, default='Tile', max_length=100, null=True)),
                ('bathrooms_type', models.CharField(default='Tile, blank=True', max_length=100, null=True)),
                ('toilets_type', models.CharField(blank=True, default='Tile', max_length=100, null=True)),
                ('cuisine_name', models.CharField(blank=True, default='Roast', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonBathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bathroom_floor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_no', models.CharField(blank=True, max_length=10, null=True)),
                ('toilet_floor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=30, null=True)),
                ('manager_ratio', models.CharField(max_length=30, null=True)),
                ('manager_full_address', models.CharField(max_length=200, null=True)),
                ('manager_telephone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30, null=True)),
                ('owner_ratio', models.CharField(max_length=30, null=True)),
                ('owner_full_address', models.CharField(max_length=200, null=True)),
                ('owner_telegraphic_address', models.CharField(max_length=200, null=True)),
                ('owner_telephone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('establishment_year', models.DateField()),
                ('commision_date', models.DateField(null=True)),
                ('telex_number', models.CharField(default='', max_length=20, null=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('hotel_address', models.CharField(max_length=100)),
                ('telegraphic_address', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('ownership_nature', models.CharField(max_length=100, null=True)),
                ('hotel_area', models.CharField(default='', max_length=50, null=True)),
                ('covered_area', models.CharField(default='', max_length=50, null=True)),
                ('area_type', models.CharField(default='', max_length=100, null=True)),
                ('land_cost', models.CharField(max_length=20, null=True)),
                ('building_cost', models.CharField(max_length=20, null=True)),
                ('furniture_cost', models.CharField(max_length=20, null=True)),
                ('equipment_cost', models.CharField(max_length=20, null=True)),
                ('working_capital', models.CharField(max_length=20, null=True)),
                ('total_investment', models.CharField(max_length=20, null=True)),
                ('floor_numbers', models.CharField(blank=True, default='1', max_length=100, null=True)),
                ('room_numbers', models.CharField(blank=True, default='1', max_length=100, null=True)),
                ('room_nature', models.CharField(choices=[('single bed room', 'SINGLE BED ROOM'), ('double bed room', 'DOUBLE BED ROOM'), ('suite room', 'SUITE ROOM')], max_length=100, null=True)),
                ('visitor_room_detail', models.CharField(max_length=200, null=True)),
                ('visitor_room_area', models.CharField(max_length=100, null=True)),
                ('reception_hall_detail', models.CharField(max_length=200, null=True)),
                ('reception_hall_area', models.CharField(max_length=100, null=True)),
                ('cloak_room_detail', models.CharField(max_length=200, null=True)),
                ('cloak_room_area', models.CharField(max_length=100, null=True)),
                ('reading_room_detail', models.CharField(max_length=200, null=True)),
                ('reading_room_area', models.CharField(max_length=100, null=True)),
                ('restaurant_detail', models.CharField(max_length=200, null=True)),
                ('restaurant_area', models.CharField(max_length=100, null=True)),
                ('staircase_no', models.CharField(default='', max_length=20, null=True)),
                ('lifts_no', models.CharField(default='', max_length=20, null=True)),
                ('car_park', models.CharField(default='', max_length=20, null=True)),
                ('area_of_compound', models.CharField(default='', max_length=50, null=True)),
                ('area_of_garden', models.CharField(default='', max_length=100, null=True)),
                ('construction_completion_date', models.DateField(default=None, null=True)),
                ('renovation_last_date', models.DateField(default=datetime.date(2010, 1, 1), null=True)),
                ('building_files', models.FileField(blank=True, default=None, null=True, upload_to='building_files/')),
                ('phones_provided', models.CharField(max_length=100, null=True)),
                ('hotel_premises', models.CharField(max_length=100, null=True)),
                ('restaurant_name', models.CharField(max_length=100, null=True)),
                ('restaurant_detail_files', models.FileField(null=True, upload_to='restaurant_files/')),
                ('monthly_guests', models.CharField(max_length=100, null=True)),
                ('business_season', models.CharField(max_length=100, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='hotel.hotelowner')),
            ],
        ),
    ]
