# Generated by Django 4.0.5 on 2022-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmanager',
            name='manager_telegraphic_address',
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='business_season',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='hotel_premises',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='monthly_guests',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='phones_provided',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='area_of_compound',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='area_of_garden',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='area_type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='building_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='car_park',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='construction_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='covered_area',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='equipment_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='floor_numbers',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='furniture_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='hotel_area',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='land_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='lifts_no',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='room_numbers',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='staircase_no',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='total_investment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='working_capital',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
