# Generated by Django 4.0.5 on 2022-07-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelownercombine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelregistration',
            options={'ordering': ('hotel_name',)},
        ),
        migrations.DeleteModel(
            name='HotelOwnerCombine',
        ),
    ]
